# Generated by Django 2.1.3 on 2018-11-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0002_auto_20181118_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobs', to='matchingsite.Member'),
        ),
    ]
