# Generated by Django 2.1.3 on 2018-11-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0003_hobbies_hobuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='listOfHob',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
