# Generated by Django 2.1.3 on 2018-11-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0004_auto_20181118_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobbies',
            old_name='listOfHob',
            new_name='list_Of_Hob',
        ),
    ]
