# Generated by Django 2.1.3 on 2018-11-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0008_auto_20181121_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
    ]
