# Generated by Django 2.1.3 on 2018-11-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0012_userprofile_allowloc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='allowloc',
            new_name='allow_location',
        ),
    ]
