# Generated by Django 2.1.3 on 2018-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0014_auto_20181124_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='allow_location',
            field=models.BooleanField(default=2, null=True),
        ),
    ]
