# Generated by Django 2.1.3 on 2018-11-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchingsite', '0016_auto_20181124_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
